To Stable
jeedom/plugin-gsh pull request #97
Opened 2024-12-22 19:53 UTC by Caelion

MR To Stable

2025-01-13 21:14 UTC, Caelion commented
Avez-vous des news pour la MR s'il vous plaît ?

2025-02-04 20:01 UTC, Caelion commented
@zoic21 : est-ce la bonne procédure pour le MR ou souhaites-tu (toi ou l'équipe Jeedom) une autre façon de faire ?

2025-02-05 08:33 UTC, zoic21 commented
Bonjour,
Je vais remonter le point a l'équipe pour voir comment faire.

2025-03-17 19:44 UTC, Caelion commented
Bonjour @zoic21 ,
Aurais tu des nouvelles de l'équipe pour la procédure s'il te plaît ?
Merci
Bien à toi,

2025-04-30 18:49 UTC, Caelion commented
Bonjour
Avez vous pu avancer sur le MR ?

2025-05-23 09:04 UTC, Mips2648 requested changes
PR should be done on beta branch, not master

2025-05-23 18:45 UTC, Caelion commented
Hello Mips
Yes, PR #96 was already done in 2024 and merge on the beta branch on the 22th nov 2024
But nothing change after in master branch, that’s why I asked to merge on master as explained above

Changelog line :
```Ajout de la prise en compte des différents modes sur un équipement de type Thermostat```

2025-06-11 21:38 UTC, Caelion commented
Hello Mips,
Sorry for the delay
Changelog.md update done in #101 

Tell me if you need anything else
Regards

2025-06-29 10:29 UTC, Caelion commented
Hello Mips
Do you have any news about stable version ?
Thank you,
Regards

2025-07-01 09:21 UTC, Mips2648 commented
sorry, I didn't see the previous update
let's continue on the other thread, I'll close this one

2025-07-01 09:21 UTC, closed without merging